### ISSUE TITLE
Doesn't Support Slack Notification Plugin

### ISSUE THREAD

**Issue by mansona** [i-m-c/jenkins-inheritance-plugin#16]
Just opening this issue so i can cross post and link the 2 plugins to see if anything can be done to improve the situation and to start the discussion. If there is anything i can do to help out just let me know. 

Here is an issue i created on the slack notification plugin page: https://github.com/jenkinsci/slack-plugin/issues/6

**Comment by nevermindr** [comment]
Should be working starting from `slack-plugin-2.0`. Please refer to referenced issue on slack-plugin page.
